name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t  ${{ vars.DOCKER_USERNAME }}/spring-api:latest .
          docker push  ${{ vars.DOCKER_USERNAME }}/spring-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull your-docker-user/spring-api:latest
            # Stop and remove existing container if it exists
            docker stop spring-api-container || true
            docker rm spring-api-container || true
            # Run the new container
            docker run -d \
              --name spring-api-container \
              -p 80:8080 \
              your-docker-user/spring-api:latest